name: "Catkin release candidate"
description: "Create a ROS package release candidate branch"
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  version:
    description: "New package version. One of version and issue_title must be specified."
    required: false
  issue_title:
    description: "Issue title containing new package version. One of version and issue_title must be specified."
    required: false
  git_user:
    description: "User name of commit author."
    required: true
  git_email:
    description: "E-mail address of commit author."
    required: true
outputs:
  created_branch:
    description: "Created branch of the release candidate."
  version:
    description: "Created release version."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-pull-request"
  color: "red"
